# Generated by Django 6.0.3 on 2026-03-27 17:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userlisteningsummary',
            unique_together={('user', 'time_range', 'snapshot_date')},
        ),
        migrations.AddIndex(
            model_name='recentlyplayedentry',
            index=models.Index(fields=['user', 'played_at'], name='spotify_rec_user_id_94bba7_idx'),
        ),
        migrations.AddIndex(
            model_name='toptracksnapshot',
            index=models.Index(fields=['user', 'time_range'], name='spotify_top_user_id_1746f2_idx'),
        ),
    ]
